language: python
python:
    - "3.5"
before_script:
    - pip install python-coveralls
install: 
    - "pip install -r test_requirements.txt"
    - "python setup.py install"
script: 
    - coverage run --source marc2iiif -m py.test 
    - flake8 --exit-zero
after_success:
    - coverage report
    - coveralls
