LABEL_LOOKUP = {
    "250": "Edition Statement",
    "254": "Musical Presentation Statement",
    "255": "Cartographic Mathemtical Data",
    "256": "Computer File Characteristic",
    "257": "Country of Producing Entity",
    "258": "Philatelic Issue Data",
    "260": "Publication, Distribution, etc (Imprint)",
    "263": "Projected Publication Date",
    "264": "Production, Publication, Publication, Distribution, Manufacture, and Copyright Notice",
    "270": "Address",
    "600": "Subject Added Entry - Personal Name",
    "610": "Subject Added Entry - Corporate Name",
    "611": "Subject Added Entry - Meeting Name",
    "630": "Subject Added Entry - Uniform Title",
    "647": "Subject Added Entry - Named Event",
    "648": "Subject Added Entry - Chronological Term",
    "650": "Subject Added Entry = Topical Term",
    "651": "Subject Added Entry - Geographic Name",
    "653": "Index Term - Uncontrolled",
    "654": "Subject Added Entry - Faceted Topical Term",
    "655": "Index Term - Genre/Form",
    "656": "Index Term - Occupation",
    "657": "Index Term - Function",
    "658": "Index Term - Curriculum Objective",
    "662": "Subject Added Entry - Hierarchical Place Name",
    "690": "Local Subject",
    "691": "Local Subject",
    "692": "Local Subject",
    "693": "Local Subject",
    "694": "Local Subject",
    "695": "Local Subject",
    "696": "Local Subject",
    "697": "Local Subject",
    "698": "Local Subject",
    "699": "Local Subject",
    "700": "Added Entry - Personal Name",
    "710": "Added Entry - Corporate Name",
    "711": "Added Entry - Meeting Name",
    "720": "Added Entry - Uncontrolled Name",
    "730": "Added Entry - Uniform Title",
    "740": "Added Entry - Uncontrolled Related/Analytical Title",
    "751": "Added Entry - Geographic Name",
    "752": "Added Entry - Hierarchical Place Name",
    "753": "System Details Access to Computer File",
    "754": "Added Entry - Taxonomic Identification",
    "758": "Resource Identifier",
    "760": "Main Entry Series Entry",
    "762": "Subseries Entry",
    "765": "Original Language Entry",
    "767": "Translation Entry",
    "770": "Supplement/Special Issue Entry",
    "772": "Supplement Parent Entry",
    "773": "Host Item Entry",
    "774": "Constituent Unit Entry",
    "775": "Other Edition Entry",
    "776": "Additional Physical Form Entry",
    "777": "Issued With Entry",
    "780": "Preceding Entry",
    "785": "Succeeding Entry",
    "786": "Date Source Entry",
    "787": "Other Relationship Entry",
    "800": "Series Added Entry - Personal Name",
    "810": "Series Added Entry - Corporate Name",
    "811": "Series Added Entry - Meeting Name",
    "830": "Series Added Entry - Uniform Title",
    "841": "Holdings Coded Data Values",
    "842": "Textual Physical form Designator",
    "843": "Reproduction Note",
    "844": "Name of Unit",
    "845": "Terms Governing Use and Reproduction",
    "850": "Holding Institution",
    "852": "Location",
    "853": "Captions and Pattern - Basic Bibliographic Unit",
    "854": "Captions and Pattern - Supplementary Material",
    "855": "Captions and Pattern - Indexes",
    "856": "Electronic Location and Access",
    "863": "Enumeration and Chronology- Basic Bibligraphic Unit",
    "864": "Enumeration and Chronology - Supplementary MAterial",
    "865": "Enumeration and Chronology - Indexes",
    "866": "Textual Holdings - Basic Bibliographic Unit",
    "867": "Textual Holdings - Supplementary Material",
    "868": "Textual Holdings - Indexes",
}